// Generated by CoffeeScript 1.9.2
(function() {
  var Plugster, expect;

  expect = require('chai').expect;

  Plugster = require('../lib/Plugster');

  describe('Plugster tests', function() {
    return it('should work', function() {
      return expect(true).to.equal(true);
    });
  });

}).call(this);

//# sourceMappingURL=plugster-spec.js.map
