// Generated by CoffeeScript 1.9.2
(function() {
  var Plugster, promise, uuid;

  uuid = require('node-uuid');

  promise = require('node-promise');

  Plugster = (function() {
    function Plugster() {}

    return Plugster;

  })();

  module.exports = Plugster;

}).call(this);

//# sourceMappingURL=Plugster.js.map
