// Generated by CoffeeScript 1.9.2
(function() {
  var Plugster, promise, uuid;

  uuid = require('node-uuid');

  promise = require('node-promise');

  Plugster = (function() {
    Plugster.modules = [];

    function Plugster(moduleName, ports) {
      var module;
      module = {
        name: moduleName,
        input: port.input,
        output: {}
      };
      ports.output.forEach(function(portName) {
        return module.output[portName] = void 0;
      });
      Plugster.modules[moduleName] = module;
    }

    Plugster.wire = function(outputModule, outputPortName, inputModule, inputPortName) {
      console.log('Plugster::wire wiring module "' + outputModule.name + " port " + outputPortName + '" to module "' + inputModule.name + '" port "' + outputPortName);
      return outputModule.output[outputPortName] = inputModule.input[inputPortName];
    };

    Plugster.prototype.isWiredTo = function(outputPortName, inputModule, inputPortname) {};

    Plugster.prototype.send = function(outputPortName, data) {};

    return Plugster;

  })();

  module.exports = Plugster;

}).call(this);

//# sourceMappingURL=Plugster.js.map
